[project]
name = "airpollutionforecasting"
version = "0.0.1"

description = "Project aims to predict future PM10 concentration based on historical and future weather and pollution data."

authors = [
  { name = "P.S.W" },
]

readme = "README.md"

requires-python = ">=3.12,<3.14"

dependencies = [
    "loguru",
    "matplotlib",
    "numpy",
    "pandas",
    "python-dotenv",
    "pyyaml>=6.0.3",
    "scikit-learn",
    "tqdm",
    "typer",
]

[dependency-groups]
dev = [
    "deptry>=0.25.1",
    "mypy>=2.3.0",
    "pandas-stubs>=3.0.5.260730",
    "pre-commit>=4.6.1",
    "pytest",
    "ruff",
    "types-pyyaml>=6.0.12.20260724",
    "types-tqdm>=4.70.0.20260805",
]

notebook = [
    "ipython",
    "jupyterlab",
    "notebook",
]
